#!/bin/bash

echo "=== Tests OK ==="
./RPN "3 4 +"
./RPN "5 2 -"
./RPN "6 3 *"
./RPN "8 4 /"
./RPN "8 9 * 9 - 9 - 9 - 4 - 1 +"
./RPN "7 7 * 7 -"

echo ""
echo "=== Tests avec priorités (ordre a - b, a / b) ==="
./RPN "2 3 -"
echo "# Attendu: -1"
./RPN "9 3 /"
echo "# Attendu: 3"
./RPN "3 2 - 5 +"
echo "# Attendu: 6"
./RPN "5 1 2 + 4 * + 3 -"
echo "# Attendu: 14"

echo ""
echo "=== Tests Error ==="
./RPN "(1 + 1)"
./RPN "1 2"
./RPN "1 2 + +"
./RPN "5 0 /"
./RPN "+"